== 版本依赖关系

:frame: topbot
[width="60%",options="header"]
|====
^|Spring Cloud Version ^|Spring Cloud Alibaba Version ^|Spring Boot Version
|Spring Cloud Greenwich|0.9.0.RELEASE|2.1.X.RELEASE
|Spring Cloud Finchley|0.2.X.RELEASE|2.0.X.RELEASE
|Spring Cloud Edgware|0.1.X.RELEASE|1.5.X.RELEASE
|====

== 组件版本关系

:frame: topbot
[width="60%",options="header"]
|====
^|Spring Cloud Alibaba Version ^|Sentinel Version ^|Nacos Version ^| RocketMQ Version ^| Dubbo Version ^| Seata Version
|0.9.0.RELEASE or 0.2.2.RELEASE or 0.1.2.RELEASE |1.5.2|1.0.0|4.4.0|2.7.1|0.4.2
|0.2.1.RELEASE or 0.1.1.RELEASE |1.4.0|0.6.2|4.3.1|❌| ❌
|0.2.0.RELEASE or 0.1.0.RELEASE |1.3.0-GA|0.3.0|❌|❌| ❌
|====

== 依赖管理

Spring Cloud Alibaba BOM 包含了它所使用的所有依赖的版本。

=== RELEASE 版本

==== Spring Cloud Greenwich

如果需要使用 Spring Cloud Greenwich 版本，请在 dependencyManagement 中添加如下内容

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-alibaba-dependencies</artifactId>
    <version>0.9.0.RELEASE</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

==== Spring Cloud Finchley

如果需要使用 Spring Cloud Finchley 版本，请在 dependencyManagement 中添加如下内容

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-alibaba-dependencies</artifactId>
    <version>0.2.2.RELEASE</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----


==== Spring Cloud Edgware

如果需要使用 Spring Cloud Edgware 版本，请在 dependencyManagement 中添加如下内容

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-alibaba-dependencies</artifactId>
    <version>0.1.2.RELEASE</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

=== BUILD-SNAPSHOT 版本

如果您想使用最近的 SNAPSHOT 版本，首先需要在你的 maven 配置中加入 Spring BUILDSNAPSHOT 仓库，可以在 Maven 配置文件中的 settings.xml 或者 Java 工程的 pom.xml 中配置，

[source,xml]
----
<repositories>
    <repository>
        <id>spring-snapshot</id>
        <name>Spring Snapshot Repository</name>
        <url>https://repo.spring.io/snapshot</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
----

NOTE: 请注意， BUILD-SNAPSHOT 版本随时可能更新	


==== Spring Cloud Greenwich

如果需要使用 Spring Cloud Greenwich 版本，请在 dependencyManagement 中添加如下内容

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-alibaba-dependencies</artifactId>
    <version>0.9.1.BUILD-SNAPSHOT</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----


==== Spring Cloud Finchley

如果需要使用 Spring Cloud Finchley 版本，请在 dependencyManagement 中添加如下内容

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-alibaba-dependencies</artifactId>
    <version>0.2.3.BUILD-SNAPSHOT</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

==== Spring Cloud Edgware

如果需要使用 Spring Cloud Edgware 版本，请在 dependencyManagement 中添加如下内容

[source,xml]
----
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-alibaba-dependencies</artifactId>
    <version>0.1.3.BUILD-SNAPSHOT</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----
